spring.datasource.url=jdbc:mysql://mysql-1b5a2329-fgfg91044-c75a.l.aivencloud.com:16343/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_SERVICE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
